# Generated by Django 3.1.7 on 2021-04-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_comment_like_post_userfollowing'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='user',
            name='profileurl',
            field=models.CharField(default='ckruf', max_length=32),
            preserve_default=False,
        ),
    ]
