# Generated by Django 3.1.7 on 2021-04-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20210409_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profileurl',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
